State configurable
surfstudio/iOS-Utils pull request #63
Opened 2020-08-20 09:33 UTC by ngagarinov

Добавлены семейство протоколов StateConfigurable и MultiStatesPresentable для удобной работы с loading/view/empty стейтами

2020-08-20 09:44 UTC, chausovSurfStudio commented
я, ребят, сразу такую вещь вброшу: работа проведена большая, Никита молодец)
но
сколько я видел этих MultiStatePresentable - у всех они разные: где-то можно дернуть PTR, где-то нельзя (вариант настройки empty/error-view), где-то title+message, а где-то просто title, кнопка может быть, может не быть, а может их несколько будет, да и вид лоадера может быть не обязательно один... да, так-то это все можно навесить сверху, расширив еще каким-нибудь протоколом, но немного запутанно может быть. Я это к тому, что была у нас задумка с проектом, куда бы мы сваливали такие вот reuse компоненты, которые вроде и реюзаются, но не сильно хорошо, копировали бы эти компоненты туда - а дальше при старте новых проектов просто вставляли бы в него эти решения и изменяли бы под себя. Вот эта штука, на мой взгляд - как раз именно такого рода и должна быть там

2020-08-20 09:55 UTC, ngagarinov commented
Ну так тут же нет дефолтной реализации Error/Empty стейтов, для этого есть протокол ErrorViewAbstract, верстаешь свою вьюху и кастомизируешь как хочешь, а то что ты предлагаешь наверное уже какая-то другая задача, тут кмк просто вынесены протоколы для удобной работы с этими стейтами. То что шиммер может быть какой-то другой, тут да, возможно стоит подумать над расширением этого

2020-08-20 10:32 UTC, dmitry2101 reviewed
Полностью поддерживаю @chausovSurfStudio. Подобные вещи тяжело унифицировать
На примере рив гоша: брали реализацию с других проектов и переделывали под себя. Времени много не занимает)

2020-08-20 10:32 UTC, dmitry2101 commented on README.md
> +`LoadingSubviewAbstract` и `LoadingSubviewConfigurable` - протоколы для реализации и конфигурации loadingSubview
Описание этих протоколов не дало мне понимания того, как пользоваться LoadingView

2020-08-20 10:32 UTC, dmitry2101 commented on README.md
> +`MultiStatesPresentable` - протокол, реализующий методы для показа/скрытия стейтов, так же служит для определения контейнера стейтов и верхних отступов, применяется на UIViewController или UIView
А вот это - зло, как по мне. Со временем, при появлении разных кейсов empty/error стейтов протокол начинает разрастаться очень сильно и становится неюзабельным (возможно и юзабельным, но без пол литра не разберешься). Появляются всякие новые параметры, присущие конкретным кейсам и тд

Примеры: рандеву, магнит

2020-08-20 10:32 UTC, dmitry2101 commented on Utils/Utils/StateConfigurable/MultiStatesPresentable.swift
> +    func showErrorView(info: ViewStateInfo, _ callback: (() -> Void)?) {}
Что если у состояния ошибки будут разные картинки? Ну или опциональная кнопка/птр?

2020-08-20 11:12 UTC, ngagarinov commented on Utils/Utils/StateConfigurable/MultiStatesPresentable.swift
> +    func showErrorView(info: ViewStateInfo, _ callback: (() -> Void)?) {}
ну, ErrorView ты сам верстаешь и для кнопки/птр есть колбек, а вот если на разных экранах будет разные картинки, тут посложней, для каждого экрана верстать наверное не хочется

2020-08-20 11:26 UTC, ngagarinov commented on README.md
> +`LoadingSubviewAbstract` и `LoadingSubviewConfigurable` - протоколы для реализации и конфигурации loadingSubview
хм, а что непонятного? пониже есть пример, где сказано что нужно сверстать loadingSubview, и если эти протоколы используются для реализации и конфигурации, то ты применяешь их к своему loadingSubview, реализуешь необходимые методы и... готово
там даж комменты к методам в коде есть

2020-08-20 11:28 UTC, ngagarinov commented on README.md
> +`MultiStatesPresentable` - протокол, реализующий методы для показа/скрытия стейтов, так же служит для определения контейнера стейтов и верхних отступов, применяется на UIViewController или UIView
согласен что кейсов может быть сколько угодно и унифицировать эту штуку достаточно непросто, но задача была все это дело вынести, если есть какие-то конкретные предложения что можно улучшить, будет клево. со своей стороны я постарался сделать это дело расширяемым

2020-09-01 10:31 UTC, AlexKuzyaev approved these changes

2020-10-26 05:27 UTC, LastSprint commented
Здесь набор протоколов позволяет сделать любой стейт который нужен. И для этого не надо расширять протоколы - там все управляется через объекты. Конкретно эта реализация не используется на магните и не уверен что она используется на риве. 
В триколоре Хренова куча разных стейтов и эта штука покрыла их все. Если будет кейс на котором у этой утилиты не хватило API, то надо будет разобрать кейс.
Это не набор базовых имплементаций - это минифреймворк для унификации работы с этими состояниями.

2020-10-30 06:24 UTC, LastSprint commented on README.md
> +extension viewController: MultiStatesPresentable {
А зачем писать этот экстеншн, если уже есть реализация через расширения протокола? 
```
public extension MultiStatesPresentable where Self: UIViewController
```

2020-10-30 06:30 UTC, LastSprint commented on README.md
> +- [StateConfigurable] - семейство протоколов для упрощения реализации loading/view/empty/ стейтов экрана
Ссылки нет

2020-10-30 06:33 UTC, LastSprint commented on README.md
> +        return ErrorView()
Может вместе с этим вытащить и дефолтную ErrorView из триколора. И добавить возможность установить ей какие-то параметры. Кажется что ти вьюги на всех проектах одинаковые

2020-10-30 06:34 UTC, LastSprint requested changes
Отписал комменты.  + поправишь плз именования. 
Типа `ErrorViewAbstract` -> `ErrorView` а конкретная имплементация уже должна иметь приставку типа `SpecificErrorView` в случае если выносить дефолтную то у нее будет `DefaultErrorView`. Та же фигня с отвальными протоколами у которых в имени указано Abstract

2020-10-30 09:27 UTC, ngagarinov commented on README.md
> +extension viewController: MultiStatesPresentable {
Не очень корректный пример, пожалуй, дефолтная реализация есть, да, тут я хотел показать, что вот надо подписать контроллер под протокол и еще в нем можно указать вью, которая будет контейнером для ваших вьюшек состяний. Перепишу тогда, чтоб понятней было

2020-10-30 09:43 UTC, ngagarinov commented on README.md
> +        return ErrorView()
Окей, я вытащу, но все-таки оставлю возможность сверстать свою

2020-10-30 13:54 UTC, ngagarinov commented on README.md
> +        return ErrorView()
Добавил дефолтную вьюху, описал в ридми как этим пользоваться, ничего лучше не придумал. оставил возможность сверстать свою

2020-10-30 16:52 UTC, ngagarinov commented on README.md
> +        return ErrorView()
проверил все стейты, все работает, даже создание собственной вьюхи

2020-11-01 20:30 UTC, chausovSurfStudio reviewed
вот смотрю я что получилось в итоге, можете закидать камнями, но я остаюсь на своем)
* есть замечательный enum ViewState, в котором есть кейс ошибки и кейс empty-вьюхи. А что делать, если empty-вьюхи в зависимости от экрана могут быть разными? Прям совсем разными. На одной текст+сообщение+картинка, на другой просто текст, при том совершенно по-другому отображаемый, с другой версткой. Можно было бы заюзать другую вьюху, но ErrorDataProvider не позволяет как-то указать параметры при получении errorView, поэтому если оба вида empty-view на одном экране будут отображаться одновременно - мы обречены опираться на контент ViewStateConfiguration и по-разному конфигурировать верстку, не говоря уже о том, что провайдеры у empty-view и у error-view одни и те же, что дополнительные проблемы в себе будет нести, если там верстка будет разная. Но это еще +/- решаемо
* во ViewStateConfiguration есть actionStyle: UIStyle от UIButton - а что нам делать, если у нас не чисто UIButton, а нечто другое? какой-то его наследник, обертка над кнопкой с доп-элементами и тп
* там же есть параметр messageTopOffset - прекрасно подойдет, если контент empty/error-вьюх будет отталкиваться от верха экрана, но есть случаи, когда положение контента задается относительно центра
* состояние loading подразумевает, что мы будет юзать BaseLoadingView, а что делать, если надо показать крутилку на полупрозрачном фоне? или же просто крутилку на белом фоне поверх текущего экрана?
* что делать, если на error/empty-вью две кнопки?
* или если там вообще карусель?) (тут на самом деле можно подумать и как-то закрыть асбтракцией ViewStateConfiguration, давая возможность указывать там те данные, что нужны на конкретно взятом проекте)

И все эти примеры не из воздуха, а из конкретных проектов. Да, вы можете сказать, что задача вынести что-то общее, набить шишки, унифицировать, подправить и тд - но в конечном итоге: зачем? Любая унификация несет в себе конкретную цель, и у нас она зачастую состоит в том, чтобы делать качественнее и быстрее. Но поможет ли качественнее и быстрее делать свою работу коробка, в которую надо что-то постоянно допиливать? Если кишки этой коробки у вас на проекте лежат сорцами - вы можете в любой момент подпилить их под себя, а не делать отдельный форк, перекатываться на него, ждать апрува от коллег, сидя все это время на своем форке.

Поэтому я бы все же рекомендовал MultiStatesPresentable (кстати вот вопрос о нейминге, меня как-то Комаров заставил задуматься, когда правку в код стайл вносил - правильно Presentable или же Presenter? ну то есть конечный компонент - viewController - не показывает себя в качестве MultiStateView, а умеет сам их показывать... но эт так, оффтоп :) ) оставить в рамках какого-нибудь BestPracticeProject - копируя при старте нового проекта данный остов будет сложно от него куда-то не туда отклониться, так что преемственность/унификация останется так или иначе, будут отличаться лишь детали. А вот часть с BaseLoadingView знатная, ее бы я в утилитах оставил бы

2020-11-02 15:31 UTC, LastSprint commented
> вот смотрю я что получилось в итоге, можете закидать камнями, но я остаюсь на своем)
> 
> * есть замечательный enum ViewState, в котором есть кейс ошибки и кейс empty-вьюхи. А что делать, если empty-вьюхи в зависимости от экрана могут быть разными? Прям совсем разными. На одной текст+сообщение+картинка, на другой просто текст, при том совершенно по-другому отображаемый, с другой версткой. Можно было бы заюзать другую вьюху, но ErrorDataProvider не позволяет как-то указать параметры при получении errorView, поэтому если оба вида empty-view на одном экране будут отображаться одновременно - мы обречены опираться на контент ViewStateConfiguration и по-разному конфигурировать верстку, не говоря уже о том, что провайдеры у empty-view и у error-view одни и те же, что дополнительные проблемы в себе будет нести, если там верстка будет разная. Но это еще +/- решаемо
> * во ViewStateConfiguration есть actionStyle: UIStyle от UIButton - а что нам делать, если у нас не чисто UIButton, а нечто другое? какой-то его наследник, обертка над кнопкой с доп-элементами и тп
> * там же есть параметр messageTopOffset - прекрасно подойдет, если контент empty/error-вьюх будет отталкиваться от верха экрана, но есть случаи, когда положение контента задается относительно центра
> * состояние loading подразумевает, что мы будет юзать BaseLoadingView, а что делать, если надо показать крутилку на полупрозрачном фоне? или же просто крутилку на белом фоне поверх текущего экрана?
> * что делать, если на error/empty-вью две кнопки?
> * или если там вообще карусель?) (тут на самом деле можно подумать и как-то закрыть асбтракцией ViewStateConfiguration, давая возможность указывать там те данные, что нужны на конкретно взятом проекте)
> 
> И все эти примеры не из воздуха, а из конкретных проектов. Да, вы можете сказать, что задача вынести что-то общее, набить шишки, унифицировать, подправить и тд - но в конечном итоге: зачем? Любая унификация несет в себе конкретную цель, и у нас она зачастую состоит в том, чтобы делать качественнее и быстрее. Но поможет ли качественнее и быстрее делать свою работу коробка, в которую надо что-то постоянно допиливать? Если кишки этой коробки у вас на проекте лежат сорцами - вы можете в любой момент подпилить их под себя, а не делать отдельный форк, перекатываться на него, ждать апрува от коллег, сидя все это время на своем форке.
> 
> Поэтому я бы все же рекомендовал MultiStatesPresentable (кстати вот вопрос о нейминге, меня как-то Комаров заставил задуматься, когда правку в код стайл вносил - правильно Presentable или же Presenter? ну то есть конечный компонент - viewController - не показывает себя в качестве MultiStateView, а умеет сам их показывать... но эт так, оффтоп :) ) оставить в рамках какого-нибудь BestPracticeProject - копируя при старте нового проекта данный остов будет сложно от него куда-то не туда отклониться, так что преемственность/унификация останется так или иначе, будут отличаться лишь детали. А вот часть с BaseLoadingView знатная, ее бы я в утилитах оставил бы

***ть
Я проектировал вообще другое. Ты прав

2020-11-03 10:36 UTC, ngagarinov commented
@LastSprint готово

2020-11-13 09:04 UTC, LastSprint approved these changes

2020-11-16 12:14 UTC, merged