Security service
surfstudio/iOS-Utils pull request #65
Opened 2020-08-22 17:14 UTC by ngagarinov

Добавлен SecurityService, который умеет шифровать/дешифровать данные по ключу, а так же содержит keychain сервис

2020-09-01 10:31 UTC, AlexKuzyaev commented
Не собралось на CI

2020-10-30 06:20 UTC, LastSprint requested changes
Надо бы еще тесты вынести из триколора

2020-11-01 10:00 UTC, ngagarinov commented
> Надо бы еще тесты вынести из триколора

Все тесты падают с ошибкой "Required entitlement isn't present ", судя по всему у таргета нет доступа к keychain, 
в данном [гайде ](https://medium.com/@ryuichi/setup-host-app-for-keychain-tests-in-xcode-8-97222611917e#.z3zpqwnzt) предлагают создать фиктивный таргет и выбрать как Host Application для тест таргета, тогда вроде как взлетит, но мне что-то не нравится.

2020-11-02 15:35 UTC, LastSprint commented
Все тесты падают с ошибкой "Required entitlement isn't present ", судя по всему у таргета нет доступа к keychain,
в данном гайде предлагают создать фиктивный таргет и выбрать как Host Application для тест таргета, тогда вроде как взлетит, но мне что-то не нравится. Больше ничего, что бы помогло, не нагуглил.

Не, это норм решение. Так и должно быть

2020-11-03 11:16 UTC, ngagarinov commented
@LastSprint готово

2020-11-16 07:19 UTC, LastSprint approved these changes

2020-11-16 07:19 UTC, merged