IDPT 816 Поправить issue с Device
surfstudio/iOS-Utils pull request #88
Opened 2021-11-12 13:30 UTC by kombatkos

# Что сделано

- Создал пакет DevicePack
- Обновил данные в пакете (добавил новые устройства)

# На что обратить внимание

- Пытался создать пакет Device, вместо этого создавалась простая папка

2021-11-16 07:27 UTC, Alelenka requested changes
Основной вопрос такой - по идее этот код добавлен не как утилита, а как код для утилиты `UIDevice`? Тогда предлагаю его добавить именно в нее и как код.
Иначе надо оформлять отдельной утилитой (но не уверена что есть смылс)
+ в любом случае надо поправить документацию для `UIDevice`
И в readme для `Device` прописать что это такая то библиотека, но она забыта и мы ее затянули себе и тут ее поддерживаем

2021-11-16 07:27 UTC, Alelenka commented on Utils/Device/Example macOS/ViewController.swift
> +        switch Device.size() {
А где 14 и 16 прошки?

2021-11-16 07:27 UTC, Alelenka commented on Utils/Device/Example/ViewController.swift
> +        super.viewDidLoad()
Раз уж новое добавлено, то стоит и примеры поправить

2021-11-16 07:27 UTC, Alelenka commented on Utils/Device/Source/Size.swift
> +    case unknownSize = 0
Тут тоже не все девайсы перечислены

2021-11-16 07:27 UTC, Alelenka commented on Utils/Device/Source/Version.swift
> +    case iPhone12Pro_Max
У нас же уже 13 есть - надо добавить

2021-11-16 07:27 UTC, Alelenka commented on Utils/Device/Source/Version.swift
> +    case iPadMini5
и ipad'ов уже больше, есть iPadMini 6 поколения да и прошек навыходило

2021-11-16 07:27 UTC, Alelenka commented on Utils/Device/Source/Version.swift
> +    case unknown
круто еще часы, apple tv и home pod  добавить - но это уже задание со звездочкой

2021-11-19 09:14 UTC, Alelenka reviewed
Сорян что так придираюсь, хочется просто чтобы было все идеально и ничего не забыто

2021-11-19 09:14 UTC, Alelenka commented on README.md
> +Набор вычисляемых проперти для определения размера экран телефона. Данный набор утилит основывается на библиотеке [Device](https://github.com/Ekhoo/Device). Как и любая другая библиотека определяющая
```suggestion
Набор вычисляемых проперти для определения размера экрана телефона. Данный набор утилит основывается на библиотеке [Device](https://github.com/Ekhoo/Device). Как и любая другая библиотека определяющая текущий телефон она требует поддержки в случае выхода новых, но эта библиотека была заброшена автором, поэтому мы добавили ее локально в папку UIDevice/Support и поддерживаем сами. 
```

2021-11-19 09:14 UTC, Alelenka commented on Utils/Utils/UIDevice/Support/iOS/Device.swift
> +                case .iPadMini, .iPadMini2, .iPadMini3, .iPadMini4, .iPadMini5:
в iPadMini6 потерялся, но у него вроде 8.3 размер, видимо надо по размерам пробежаться

2021-11-19 09:20 UTC, Alelenka commented on Utils/Device/Source/Size.swift
> +    case unknownSize = 0
Кажется  тут надо 8,3 для ipadMini6 добавить

2021-11-26 09:22 UTC, Alelenka commented on README.md
> +Набор вычисляемых проперти для определения размера экран телефона. Данный набор утилит основывается на библиотеке [Device](https://github.com/Ekhoo/Device). Как и любая другая библиотека определяющая
Тут решил не менять? Если да - то обосную почему)

2021-11-26 09:23 UTC, Alelenka approved these changes

2021-12-19 21:06 UTC, chausovSurfStudio approved these changes
к коду вопросов нет, правки - мелочи, на которые можно закрыть глаза, так что не вижу смысла дальше держать ПР, но если захочется внести правки - такое рвение только приветствуется)

2021-12-19 21:06 UTC, chausovSurfStudio commented on Utils/Utils/UIDevice/Support/macOS/DeviceMacOS.swift
> +        let versionCode = Device.getVersionCode()
здесь аналогичная проблема - параметр приходит, но не используется

2021-12-19 21:06 UTC, chausovSurfStudio commented on Utils/Utils/UIDevice/Support/macOS/DeviceMacOS.swift
> +    static public func type() -> Type {
и чисто вопрос - а как это работает?) почему `Type` а не `DeviceType`?) видимо я что-то упустл, хочется понять что 🙃

2021-12-19 21:21 UTC, chausovSurfStudio commented
а, да: если будешь правки вносить - там два ворнинга от swiftlint, тоже можно поправить

2021-12-20 06:18 UTC, kombatkos commented on Utils/Utils/UIDevice/Support/macOS/DeviceMacOS.swift
> +    static public func type() -> Type {
Тут опечатка была, не обратил внимания

2021-12-20 06:24 UTC, kombatkos commented on Utils/Utils/UIDevice/Support/macOS/DeviceMacOS.swift
> +    static public func type() -> Type {
<img width="453" alt="Снимок экрана 2021-12-20 в 10 24 28" src="https://user-images.githubusercontent.com/56546669/146721419-89d2654d-faa3-441f-a078-bec531ce5134.png">
Хотя есть вот такой метод для Мак ос

2021-12-20 07:29 UTC, merged