Исправление бага с lineHeight в String Attributes
surfstudio/iOS-Utils pull request #90
Opened 2022-04-19 11:13 UTC by paradi2e

# What is done

- высота теперь выставляется не через расстояние между строк и не зависит от шрифта. меняются параметры minLineHeight и maxLineHeight 

# What to look for

- если высота строки меньше высоты шрифта, то будет обрезание строк. 

# How to check

- установить в проект под из ветки (добавить в podfile следующую строку: 

>  pod 'SurfUtils/StringAttributes', :git => "https://github.com/surfstudio/iOS-Utils.git", :branch => 'IDPT-799-fix-string-attributes-lineHeight'

- вывести на экран несколько лейблов с разными параметрами .lineHeight(CGFloat)

2022-04-26 11:50 UTC, chausovSurfStudio requested changes
задам еще вопрос дизайнерам, чую подвох с фигмой, надо убедится что такой подход (указывание lineHeight, а не lineSpacing) на всех фигмовских проектах, что она именно так работает (типа если lineHeight == 20, то высота лейбла с одной строкой 20, двумя - 40, и тд... а то до правок этих, пока указывался lineSpacing, были разночтения - фигма тупо умножала кол-во строк на lineHeight, а у нас получалось, что кол-во строк умножить на lineHeight минус какое-то значение, потому что высота первой строки чуточку меньше. Вот хочу точно узнать как фигма работает в этом плане)

2022-04-26 11:50 UTC, chausovSurfStudio commented on Utils/Utils/String/String+Attributes.swift
> +                paragraph.maximumLineHeight = lineHeight
смотри, насчет этого подхода

Есть такая вещь как изменение размера шрифта в зависимости от размера контейнера, autoshrink, не частно, но применяется.

Я сделал тестовый проект, в котором
- бросил на экран по центру лейбл, сделал ему констрейнт на высоту, сделал его равным 25
- из кода ставлю ему текст, настройки как в либе, но просто кодом, без либы, чисто чтобы ситуацию воспроизвести
- ставлю maximum/minimum в 55

получается что-то типа

```swift
        let text = "Тестовый текст"
        let font = UIFont.systemFont(ofSize: 40, weight: .medium)
        let paragraphStyle = NSMutableParagraphStyle()
        paragraphStyle.minimumLineHeight = 55
        paragraphStyle.maximumLineHeight = 55
        titleLabel.attributedText = NSAttributedString(string: text,
                                                       attributes: [
                                                        .font: font,
                                                        .paragraphStyle: paragraphStyle
                                                       ])

        titleLabel.numberOfLines = 1
        titleLabel.minimumScaleFactor = 0.3
        titleLabel.adjustsFontSizeToFitWidth = true
        titleLabel.baselineAdjustment = .alignCenters
```

в итоге вот такая вот картинка, ибо высота строки всегда будет 55

<img width="376" alt="Снимок экрана 2022-04-26 в 14 41 22" src="https://user-images.githubusercontent.com/8776643/165292368-5fa03d8e-283a-40a4-8667-75270c8401f3.png">

потом я пошел в тот issue, который ты из коммента стер, попал из него вот на такую [статью](https://habr.com/ru/company/redmadrobot/blog/280029/), и сделал как в ней - вместо min/max попробовал рулить `lineHeightMultiple`

```swift
        let paragraphStyle = NSMutableParagraphStyle()
        paragraphStyle.lineHeightMultiple = 55 / font.lineHeight
```

и получилось как-то так

<img width="376" alt="Снимок экрана 2022-04-26 в 14 44 16" src="https://user-images.githubusercontent.com/8776643/165292837-3cd21c6d-aa93-421d-bf04-09477175f1b5.png">

в остальных бытовых случаях - вроде как тоже работает. Ну и расчет высоты руками тоже норм отрабатывает. Так что предлагаю задуматься над именно таким подходом как более универсальным) (ну и да, здесь опять завязка на font, но мб попытаться его найти среди других атрибутов, а не жестко указывать в lineHeight, как раньше? а если такие не найдется - то уже устанавливать max/min как вот у тебя...)

2022-04-28 09:58 UTC, chausovSurfStudio commented on Utils/Utils/String/String+Attributes.swift
> +                paragraph.maximumLineHeight = lineHeight
<img width="643" alt="Снимок экрана 2022-04-28 в 12 58 08" src="https://user-images.githubusercontent.com/8776643/165728111-24f10bfc-f262-4899-9a26-9c38d53af82d.png">

ну кстати аргумент в пользу такого подхода - фигма на самом деле его и предлагает)

2022-05-27 06:51 UTC, chausovSurfStudio commented on Utils/Utils/String/String+Attributes.swift
> +    /// Text line minimum and maximum height
комменты к lineHeight и lineSpacing добавил, baselineOffset - решил не добавлять, нечего документацию переписывать

2022-05-27 06:54 UTC, chausovSurfStudio commented on Utils/Utils/String/String+Attributes.swift
> +                paragraph.maximumLineHeight = lineHeight
посоветовался с отделом, ответил только Сережа) но в целом норм, мне нравится
так что сделано как в итоге - кейс `.lineHeight(CGFloat)`, параметром передается высота строки в поинтах, если среди других атрибутов передается шрифт - то будет заюзан `lineHeightMultiple`, иначе - `minimum/maximumLineHeight`

2022-05-27 08:20 UTC, chausovSurfStudio commented
протестил на отдельном проекте, опишу результаты

фиксируем высоту в 30pt, фиксируем шрифт и lineHeight, разрешаем уменьшать кегль шрифта если текст не влазит, одна строка, вводим длинный текст - кегль уменьшился
<img width="850" alt="Снимок экрана 2022-05-27 в 10 59 01" src="https://user-images.githubusercontent.com/8776643/170659375-69a51e1e-83dc-4361-bcaf-52d2e103dc49.png">

фиксируем высоту в 30pt, фиксируем шрифт и lineHeight, разрешаем уменьшать кегль шрифта если текст не влазит, одна строка, вводим короткий текст - кегль уменьшился
<img width="844" alt="Снимок экрана 2022-05-27 в 11 00 19" src="https://user-images.githubusercontent.com/8776643/170659626-8a4504c4-2254-454c-be30-01c1003ae277.png">

не фиксируем высоту, фиксируем шрифт и lineHeight, одна строка, вводим короткий текст - высота блока соответствует lineHeight
<img width="839" alt="Снимок экрана 2022-05-27 в 11 02 13" src="https://user-images.githubusercontent.com/8776643/170659668-da94da3d-d213-4e36-be03-bcbcbd456e73.png">

не фиксируем высоту, фиксируем шрифт и lineHeight, много строк разрешаем, текст на две строки - высота блока соответствует lineHeight * кол-во строк
<img width="844" alt="Снимок экрана 2022-05-27 в 11 03 17" src="https://user-images.githubusercontent.com/8776643/170659798-50a56133-eab7-4013-8d2a-9bd404d229ac.png">

убираем шрифт из атрибутов, но оставляем lineHeight - высота блока осталась
<img width="838" alt="Снимок экрана 2022-05-27 в 11 04 28" src="https://user-images.githubusercontent.com/8776643/170659920-2743f3ae-ff64-4a79-8dde-9183341a8983.png">

вроде все прошло 🤷‍♂️

2022-05-30 17:51 UTC, Alelenka approved these changes
Работает...
Единственное я бы подумала как описать изменения для тех кто в старых проектах будет переходить что надо font добавить отдельно, а не в lineHeight, а то все сломается.
Может быть комментарий в readme или доп readme в папке Strings

2022-05-31 08:09 UTC, chausovSurfStudio approved these changes

2022-05-31 08:11 UTC, chausovSurfStudio commented
> Работает... Единственное я бы подумала как описать изменения для тех кто в старых проектах будет переходить что надо font добавить отдельно, а не в lineHeight, а то все сломается. Может быть комментарий в readme или доп readme в папке Strings

я это обычно указываю в описании релиза. По-хорошему бы еще changelog с изменениями вести, тогда и там можно будет указывать.

Так что в релизе точно укажу, а там дальше будут задачки по настройке опрятного вида репозитория, тогда сделаем и changelog, и туда описания к последним релизам выкатим

2022-05-31 08:25 UTC, merged